spring:
  application:
    name: MySelectShop

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: ${{secrets.DATABASE_SECRET_KEY}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

jwt:
  secret:
    key: ${{secrets.JWT_SECRET_KEY}}

  admin-token: ${{secrets.ADMIN_TOKEN}}

naver:
  client:
    id: ${{secrets.NAVER_SECRET_ID}}
    secret: ${{secrets.NAVER_SECRET_KEY}}